// Copyright (c) 2025, qleonardolp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROBOT_IMPEDANCE_ANALYZER__IMPEDANCE_ID_HPP_
#define ROBOT_IMPEDANCE_ANALYZER__IMPEDANCE_ID_HPP_

#include <Eigen/Dense>

#include <cmath>
#include <chrono>
#include <map>
#include <memory>
#include <string>
#include <vector>

#include <kinematic_pose_msgs/msg/kinematic_pose.hpp>
#include <std_msgs/msg/float64_multi_array.hpp>
#include <lifecycle_msgs/msg/state.hpp>
#include <lifecycle_msgs/msg/transition.hpp>
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <rclcpp_lifecycle/state.hpp>

#include <robot_impedance_analyzer/common.hpp>
// auto-generated by generate_parameter_library
#include <robot_impedance_analyzer/impedance_id_parameters.hpp>

namespace impedance_identification
{
// Status msg deviation zero index
const size_t kDevId = 6;
// Status msg twist deviation zero index
const size_t kVelId = 12;
// Status msg accel deviation zero index
const size_t kAccId = 18;
// Output vector y is [e, \dot{e}, \ddot{e}]^T
const uint8_t kOutputDim = 3;

const uint8_t kSpaceDim = 1;  // TODO(@me): refact for multi-axis identification
const uint8_t kPoseDim = 7;   // position + quaternion
// Regression vector \phi is [e(k-1), \dot{e}(k-1), 1]^T
const size_t kPhiSize = kSpaceDim * (3);

typedef Eigen::Matrix<double, kPhiSize, kPhiSize> CovarianceMatrix;

const uint8_t kPlaneWindow = 3;
// First order finite difference with five points (2, 1, 0, -1, -2)
const std::array<double, 5> kFDCoeffcient = {-1.0 / 12, 8.0 / 12, 0, -8.0 / 12, 1.0 / 12};

const double kPosDeltaThreshold = 0.030;  // ~100 km/h @ 1000 Hz
const double kAreaThreshold = 4e-7;  // Cluster (3 points) minimum area
typedef Eigen::Matrix<double, kPlaneWindow, 3> ClusterMatrix;

using KinematicPose = kinematic_pose_msgs::msg::KinematicPose;
using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

/**
 * @brief Lifecycle Node with a subscriber (std_msgs::msg::Float64MultiArray) to identify
 * the impedance parameters (stiffness, damping, and inertia) from e, $\ \dot{e} \$, and
 * $\ \ddot{e} \$ or interaction wrench (f_{int}).
 */
class ImpedanceId : public rclcpp_lifecycle::LifecycleNode
{
public:
  explicit ImpedanceId(const std::string & node_name, bool intra_process_comms = false);

  CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_cleanup(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_shutdown(const rclcpp_lifecycle::State & previous_state) override;

  /**
   * @brief Output data callback
   */
  void output_callback(const std_msgs::msg::Float64MultiArray & status_msg);

  /**
   * @brief Recursive Least Squares (RLS) update method
   */
  void update_rls();

  /**
   * @brief Impedance space planar identification (ISPI) update method
   */
  void update_ispi();

private:
  // Low-pass filter alpha for the Nyquist frequency.
  double lpf_alpha_{0.7585469929947761};

  rclcpp::Time last_clock_;
  double delta_t_;  // time delta

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  std::size_t axis_;
  bool step_detected_;

  // System output (y) subscriber.
  rclcpp::Subscription<std_msgs::msg::Float64MultiArray>::SharedPtr output_subscriber_;
  rclcpp::Publisher<std_msgs::msg::Float64MultiArray>::SharedPtr param_publisher_;
  std_msgs::msg::Float64MultiArray estimates_;

  // Theta estimation from RLS and ISPI fusion
  Eigen::Vector3d fused_theta_;

  /* Recursive Least Squares (RLS) class members */
  double lambda_{1.0 - 2e-6};  // RLS forgetting factor
  // Estimated parameters
  Eigen::Matrix<double, kPhiSize, kSpaceDim> theta_;
  // Estimated parameters (last)
  Eigen::Matrix<double, kPhiSize, kSpaceDim> theta_last_;
  // Regression vector
  Eigen::Vector<double, kPhiSize> phi_;
  // Covariance matrix (P_k)
  CovarianceMatrix cov_k_;
  // Gain (K_k)
  Eigen::Vector<double, kPhiSize> gain_k_;
  double rls_gain_den_{1.0};

  Eigen::Vector<double, kSpaceDim * kOutputDim> new_output_;  // e, de, dde
  // Without interaction (f_{int} = 0):
  // error = dde + k/m * e + d/m * de - b
  // b = 1/m * f_int
  Eigen::Vector<double, kSpaceDim> error_;
  /* End of RLS class members */

  /* Impedance space planar identification (ISPI) class members */
  Eigen::Vector3d new_point_;     //
  Eigen::Vector3d first_point_;   //
  Eigen::Vector3d first_last_;    //
  Eigen::Vector3d cross_prod_;    //
  Eigen::Vector3d direction_v1_;  // plane direction vector 1
  Eigen::Vector3d direction_v2_;  // plane direction vector 2
  Eigen::Vector3d plane_n_;       // estimated plane normal vector
  Eigen::Vector3d plane_n_last_;  // estimated plane normal vector (last)
  Eigen::Vector3d plane_n_filt_;  // estimated plane normal vector (filtered)
  uint8_t point_counter_;         // plane points counter (<= 3)
  double cluster_area_;           // area spanned by the three points
  double dde_offset_;             // acceleration offset due to residual f_int
  double plane_d_;                // plane `d` (a*x + b*y + c*z + d = 0)
  /* End of ISPI class members */
};

}  // namespace impedance_identification

#endif  // ROBOT_IMPEDANCE_ANALYZER__IMPEDANCE_ID_HPP_
