// Copyright (c) 2025, qleonardolp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROBOT_IMPEDANCE_ANALYZER__KINEMATIC_REFERENCE_HPP_
#define ROBOT_IMPEDANCE_ANALYZER__KINEMATIC_REFERENCE_HPP_

#include <cmath>
#include <chrono>
#include <map>
#include <memory>
#include <random>
#include <string>
#include <vector>

#include <kinematic_pose_msgs/msg/kinematic_pose.hpp>
#include <std_msgs/msg/float64.hpp>
#include <lifecycle_msgs/msg/state.hpp>
#include <lifecycle_msgs/msg/transition.hpp>
#include <rclcpp/qos.hpp>
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_lifecycle/lifecycle_node.hpp>
#include <rclcpp_lifecycle/state.hpp>

#include <robot_impedance_analyzer/common.hpp>
// auto-generated by generate_parameter_library
#include <robot_impedance_analyzer/kinematic_reference_parameters.hpp>

namespace kinematic_reference
{
enum SignalType
{
  kStep,
  kSmoothStep,
  kSineWave,
  kStepSequence,
  kCPGLegTrajectory,
  kSquarewave,
  kSines,
  kChirp,
  kPRBS,
};

std::map<std::string, uint8_t> TypeMap = {
  {std::string("step"), SignalType::kStep},
  {std::string("smooth-step"), SignalType::kSmoothStep},
  {std::string("sinewave"), SignalType::kSineWave},
  {std::string("step-sequence"), SignalType::kStepSequence},
  {std::string("cpg-trajectory"), SignalType::kCPGLegTrajectory},
  {std::string("squarewave"), SignalType::kSquarewave},
  {std::string("sines"), SignalType::kSines},
  {std::string("chirp"), SignalType::kChirp},
  {std::string("PRBS"), SignalType::kPRBS},
};

const double PI_2 = 2 * M_PI;
const uint8_t kSpaceDim = 6;  // Cartesian space dimension
const uint8_t kPoseDim = kSpaceDim + 1;  // position + quaternion
const double kTimeOffset = 2.0;  // seconds
const double kSmoothStepEnd = kTimeOffset + 0.22;
const double kSmoothStepSlope = 77.0;

using KinematicPose = kinematic_pose_msgs::msg::KinematicPose;
using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

/**
 * @brief Lifecycle Node with a simple publisher and configurable reference signal
 * through the node parameters
 */
class KinematicReference : public rclcpp_lifecycle::LifecycleNode
{
public:
  explicit KinematicReference(const std::string & node_name, bool intra_process_comms = false);

  CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_cleanup(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_shutdown(const rclcpp_lifecycle::State & previous_state) override;

  /**
   * @brief Integrate the Central Pattern Generator amplitude equation
   * according to https://doi.org/10.1109/IROS58592.2024.10802762
   */
  double cpg_amplitude();

  /**
   * @brief Step signal callback
   */
  void step_callback();

  /**
   * @brief Sine signal callback
   */
  void sinewave_callback();

  /**
   * @brief Step sequence callback
   */
  void stepseq_callback();

  /**
   * @brief Central Pattern Generator callback
   */
  void cpg_callback();

  /**
   * @brief Squarewave signal callback.
   * Signal is based on Numerically Controlled Oscillator (NCO).
   */
  void squarewave_callback();

  /**
   * @brief Sines signal callback
   */
  void sines_callback();

  /**
   * @brief Pseudo Random Binary Signal (PRBS) callback
   */
  void prbs_callback();

  /**
   * @brief Chirp signal callback
   */
  void chirp_callback();

  /**
   * @brief Second order low pass filter
   */
  double lpf_biquad(const double sample);

  /**
   * @brief Update `message_` with positions_,
   * velocities_, and accelerations_.
   */
  void set_message();

private:
  std::shared_ptr<rclcpp::TimerBase> timer_;
  std::shared_ptr<rclcpp::Publisher<KinematicPose>> publisher_;
  KinematicPose message_;

  rclcpp::Time start_time_;
  double timer_period_{0};
  double ellapsed_time_{0};
  double angular_freq_{1};
  double cpg_phase_{0};

  std::vector<double> accelerations_;
  std::vector<double> velocities_;
  std::vector<double> positions_;
  std::size_t axis_;
  int signal_type_;

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // PRBS random number generator (32 bits)
  std::minstd_rand pseudo_rand;
};

}  // namespace kinematic_reference

#endif  // ROBOT_IMPEDANCE_ANALYZER__KINEMATIC_REFERENCE_HPP_
