kinematic_reference:
  ros__parameters:
    topic_name: impedance_controller/reference
    signal_type: step
    axis: 'x'
    initial_pose: [0.14931, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
    amplitude: 0.4
    mass: 10.0
    spring: 800.0
    damper: 134.164  # Î¶ = 0.75
    rate: 100
