kinematic_reference:
  ros__parameters:
    topic_name: ur5_controller/reference
    signal_type: sinewave
    axis: 'x'
    initial_pose: [0.39, 0.1, 0.55, 0.0, 0.0, 0.0, 1.0]
    amplitude: 0.10
    period: 1.0
    mass: 20.0  # no IS: 21.0669
    spring: 200.0  # no IS: 400.0
    damper: 126.491
    rate: 1000
