kinematic_reference:
  ros__parameters:
    topic_name: impedance_controller/reference
    signal_type: step-sequence
    axis: 'x'
    initial_pose: [0.30, -0.20, 0.30, 0.0, 0.0, 0.0, 1.0]
    amplitude: 0.6  # 0.5
    mass: 10.0
    spring: 800.0
    damper: 134.164  # Î¶ = 0.75
    period: 4.00
    rate: 50
    steps:
      - step_1
      - step_2
    steps_pose:
      step_1:
        pose: [0.7, -0.20, 0.30, 0.0, 0.0, 0.0, 1.0]
        time: 0.2
      step_2:
        pose: [0.7, 0.10, 0.60, 0.0, 0.0, 0.0, 1.0]
        time: 5.0