kinematic_reference:
  ros__parameters:
    topic_name: impedance_controller/reference
    signal_type: step
    axis: 'x'
    initial_pose: [0.30, -0.20, 0.30, 0.0, 0.0, 0.0, 1.0]
    amplitude: 0.6  # 0.5
    mass: 10.0
    spring: 800.0
    damper: 134.164  # Î¶ = 0.75
    period: 4.00
    rate: 200
