quadruped_control:
  ros__parameters:
    control_topics: [
      spot_fl_control/reference,
      spot_fr_control/reference,
      spot_hl_control/reference,
      spot_hr_control/reference
    ]
    body_height: -0.1
    fl_offset: [0.360, 0.20, 0.330]
    fr_offset: [0.360,-0.2003, 0.330]
    rl_offset: [-0.29, 0.20, 0.332]
    rr_offset: [-0.29,-0.2003, 0.332]
    rate: 250
