kinematic_reference:
  ros__parameters:
    topic_name: ur5_controller/reference
    initial_pose: [0.350, -0.10915, 0.75, 0.0, 0.0, 0.0, 1.0]
    signal_type: sines
    axis: 'x'
    sines_amp: [0.0254, 0.012, 0.018, 0.004, 0.003, 0.020, 0.015]
    sines_freq: [1.000, 4.500, 0.333, 9.000, 6.000, 27.00, 18.00]
    rate: 1000
    spring: 490.0
    damper: 140.0
    mass: 10.0

identification:
  ros__parameters:
    axis: x
    controller_reference_topic: ur5_controller/reference
    controller_status_topic: ur5_controller/status
    sampling_frequency: 1000.0
    cutoff_frequency: 20.0
    expected_stiffness: 490.0
    expected_damping: 140.0
    expected_mass: 10.0
