kinematic_reference:
  ros__parameters:
    topic_name: ur5_controller/reference
    initial_pose: [0.14931, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
    signal_type: step-sequence
    axis: 'x'
    mass: 20.0
    spring: 200.0
    damper: 126.491
    rate: 1000
    steps:
      - s1
      - s2
      - s3
      - s4
      - s5
      - s6
      - s7
      - s8
      - s9
      - s10
      - s11
      - s12
      - s13
      - s14
      - s15
      - s16
    steps_pose:
      s1:
        pose: [0.650, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 2.0
      s2:
        pose: [0.640, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 2.6
      s3:
        pose: [0.650, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 3.0
      s4:
        pose: [0.630, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 4.0
      s5:
        pose: [0.650, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 5.0
      s6:
        pose: [0.644, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 5.5
      s7:
        pose: [0.650, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 8.5
      s8:
        pose: [0.640, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 9.0
      s9:
        pose: [0.650, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 10.0
      s10:
        pose: [0.637, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 11.0
      s11:
        pose: [0.650, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 11.9
      s12:
        pose: [0.655, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 12.8
      s13:
        pose: [0.650, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 13.7
      s14:
        pose: [0.645, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 14.5
      s15:
        pose: [0.650, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 15.4
      s16:
        pose: [0.630, -0.10915, 0.62136, 0.0, 0.0, 0.0, 1.0]
        time: 16.2

identification:
  ros__parameters:
    controller_reference_topic: ur5_controller/reference
    controller_status_topic: ur5_controller/status
    axis: x
    expected_stiffness: 200.0
    expected_damping: 126.491
    expected_mass: 20.0
