kinematic_reference:
  ros__parameters:
    topic_name: hyl_controller/reference
    initial_pose: [0.0, 0.13, -0.4534, 0.0, -0.4792, 0.0, 0.8776]
    signal_type: PRBS  # squarewave
    amplitude: 0.050
    period: 1.7
    axis: z
    sines_amp: [0.010, 0.020, 0.005, 0.0254, 0.050, 0.018, 0.005]
    sines_freq: [0.007, 0.010, 0.066, 1.000, 7.000, 11.50, 14.00]
    rate: 1000
    spring: 640.0
    damper: 160.0
    mass: 10.0

identification:
  ros__parameters:
    axis: z
    controller_reference_topic: hyl_controller/reference
    controller_status_topic: hyl_controller/status
    sampling_frequency: 1000.0
    cutoff_frequency: 20.0
    expected_stiffness: 640.0
    expected_damping: 160.0
    expected_mass: 10.0
